#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= tiny210.o
obj-$(CONFIG_SAMSUNG_ONENAND)	+= onenand.o
obj-y	+= lowlevel_init.o
